mydreamhouse/src/Entity/Usuario.php
<?php

namespace App\Entity;

use App\Repository\UsuarioRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Mapping\ClassMetadata;

/**
 * @ORM\Entity(repositoryClass=UsuarioRepository::class)
 * @UniqueEntity(fields="email", message="Ya existe un usuario con ese correo!!!")
 */
class Usuario implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(name="email", type="string", length=255, unique=true)
     * @Assert\Email()
     */
    protected $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=15, nullable=true)
     */
    private $nombre;

    /**
     * @ORM\Column(type="string", length=25, nullable=true)
     */
    private $apellidos;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $fecha_nac;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $imagen_usu;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(?string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getApellidos(): ?string
    {
        return $this->apellidos;
    }

    public function setApellidos(?string $apellidos): self
    {
        $this->apellidos = $apellidos;

        return $this;
    }

    public function getFechaNac(): ?\DateTimeInterface
    {
        return $this->fecha_nac;
    }

    public function setFechaNac(?\DateTimeInterface $fecha_nac): self
    {
        $this->fecha_nac = $fecha_nac;

        return $this;
    }

    public function getImagenUsu(): ?string
    {
        return $this->imagen_usu;
    }

    public function setImagenUsu(?string $imagen_usu): self
    {
        $this->imagen_usu = $imagen_usu;

        return $this;
    }
}

mydreamhouse/src/Form/UsuarioType.php
<?php

namespace App\Form;

use App\Entity\Usuario;
//use Doctrine\DBAL\Types\DateType;
//use Doctrine\DBAL\Types\TextType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Validator\Constraints\File;

class UsuarioType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email', EmailType::class, [
                'label' => 'Email',
                'required' => true
            ])
            ->add('password', PasswordType::class, [
                'label' => 'Contraseña',
                'required' => true
            ])
            ->add('nombre', TextType::class, [
                'label' => 'Nombre',
                'required' => true
            ])
            ->add('apellidos', TextType::class, [
                'label' => 'Apellidos'
            ])
            ->add('fecha_nac', DateType::class, [
                'widget' => 'single_text',
                'attr' => array(
                    'max' => date('Y-m-d')
                )
            ])
            /* ->add('roles', ChoiceType::class, [
                'label' => 'Rol',
                'choices' => [
                    'Usuario' => '["ROLE_USER"]',
                    'Administrador' => '["ROLE_ADMIN"]'
                ],
                'expanded' => true,
                'multiple' => false,
                'required' => true
            ]) */
            ->add('imagen_usu', FileType::class, [
                'label' => 'Foto',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '2048k',
                        'mimeTypes' => [
                            'image/png',
                            'image/jpeg',
                            'image/gif',
                        ],
                        'mimeTypesMessage' => 'Por favor introduce un formato de imagen válido'
                    ])
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Usuario::class,
        ]);
    }
}

mydreamhouse/src/Controller/UsuarioController.php
<?php

namespace App\Controller;

use App\Entity\Usuario;
use App\Form\UsuarioType;
use App\Repository\UsuarioRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

//use function App\acceso;

/**
 * @Route("/usuario")
 */
class UsuarioController extends AbstractController
{
    /**
     * @Route("/", name="usuario_index", methods={"GET"})
     */
    public function index(UsuarioRepository $usuarioRepository, Usuario $user = null): Response
    {
        $usu = $this->getUser();

        if ($usu == null) {

            return $this->render('error/error403.html.twig');
        } else {

            if ($usuarioRepository->acceso($usu->getRoles()) == 'admin') {

                return $this->render('usuario/index.html.twig', [
                    'usuarios' => $usuarioRepository->findAll(),
                ]);
            } else {

                return $this->render('usuario/show.html.twig', [
                    'usuario' => $usu,
                ]);
            }
        }
    }

    /**
     * @Route("/new", name="usuario_new", methods={"GET","POST"})
     */
    public function new(Request $request, UserPasswordEncoderInterface $passwordEncoder): Response
    {
        $usuario = new Usuario();
        $form = $this->createForm(UsuarioType::class, $usuario);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            /** @var UploadedFile $brochureFile */
            $brochureFile = $form->get('imagen_usu')->getData();

            // this condition is needed because the 'brochure' field is not required
            // so the PDF file must be processed only when a file is uploaded
            if ($brochureFile) {
                $originalFilename = pathinfo($brochureFile->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = transliterator_transliterate('Any-Latin; Latin-ASCII; [^A-Za-z0-9_] remove; Lower()', $originalFilename);
                $newFilename = $safeFilename . '_' . uniqid() . '.' . $brochureFile->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $brochureFile->move(
                        $this->getParameter('img_usu'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

                // actualiza la propiedad 'brochureFilename' para guardar el nombre archivo
                $usuario->setImagenUsu($newFilename);
            }

            $usuario->setPassword($passwordEncoder->encodePassword($usuario, $form['password']->getData()));

            /* $usuario->setRoles(['ROLE_ADMIN']); */

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($usuario);
            $entityManager->flush();

            return $this->render('usuario/redirect.html.twig');
        }

        return $this->render('usuario/new.html.twig', [
            'usuario' => $usuario,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/show/{id}", name="usuario_show", methods={"GET"})
     */
    public function show(Usuario $usuario): Response
    {
        return $this->render('usuario/show.html.twig', [
            'usuario' => $usuario,
        ]);
    }

    /**
     * @Route("/edit/{id}", name="usuario_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Usuario $usuario, UserPasswordEncoderInterface $passwordEncoder): Response
    {
        $form = $this->createForm(UsuarioType::class, $usuario);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            /** @var UploadedFile $brochureFile */
            $brochureFile = $form->get('imagen_usu')->getData();

            // this condition is needed because the 'brochure' field is not required
            // so the PDF file must be processed only when a file is uploaded
            if ($brochureFile) {
                $originalFilename = pathinfo($brochureFile->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = transliterator_transliterate('Any-Latin; Latin-ASCII; [^A-Za-z0-9_] remove; Lower()', $originalFilename);
                $newFilename = $safeFilename . '_' . uniqid() . '.' . $brochureFile->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $brochureFile->move(
                        $this->getParameter('img_usu'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

                // actualiza la propiedad 'brochureFilename' para guardar el nombre archivo
                $usuario->setImagenUsu($newFilename);
            }

            $usuario->setPassword($passwordEncoder->encodePassword($usuario, $form['password']->getData()));

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('usuario_index');
        }

        return $this->render('usuario/edit.html.twig', [
            'usuario' => $usuario,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/delete/{id}", name="usuario_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Usuario $usuario): Response
    {
        if ($this->isCsrfTokenValid('delete' . $usuario->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($usuario);
            $entityManager->flush();
        }

        return $this->redirectToRoute('usuario_index');
    }
}

mydreamhouse/templates/usuario/_delete_form.html.twig
<form method="post" action="{{ path('usuario_delete', {'id': usuario.id}) }}" onsubmit="return confirm('Seguro que quieres borrar a este usuario?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ usuario.id) }}">
    <button class="btn btn-danger profile-button">Eliminar<img class="ml-1" src="{{ asset('data/images/white_trash.png') }}"/></button>
    
</form>

mydreamhouse/templates/usuario/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-info profile-button btn-save mb-3">
        {{ button_label|default('Guardar') }}
        <img class="ml-1" src="{{ asset('data/images/save.png') }}"/>
    </button>
{{ form_end(form) }}

mydreamhouse/templates/usuario/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editar Usuario{% endblock %}

{% block body %}

    <div class="container rounded bg-white"style="background-image: url('/data/images/fondos/casaFondoOpacity.png');" >
    <div class="row">
        <div class="col-md-4 border-right" style="background-image: url('/data/images/fondos/casaFondoOpacity.png');">
            <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                <img class="rounded-circle mt-5" src="{{ usuario.imagenUsu ? asset('data/images/usuarios/'~usuario.imagenUsu) : asset('data/images/usuarios/user-image.png') }}" width="90">
                <span class="font-weight-bold text-light">{{ usuario.nombre }}</span><span class="text-light">{{ usuario.apellidos }}</span>
                <span class="text-light">{{ usuario.email }}</span>
            </div>
        </div>
        <div class="col-md-8">
            <div class="p-3 py-5">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h2 class="text-right text-light">Editar perfil</h2>
                </div>
                {% if usuario.email == app.user.email %}
                    <div class="col-btn text-light">
                        {{ include('usuario/_form.html.twig') }}
                        <a class="btn btn-dark" href="{{ path('home') }}"><img src="{{ asset('data/images/arrow_white.png') }}" class="show-img-index"/></a>
                    </div>
                {% else %}
                <div class="col-btn text-light">
                    {{ include('usuario/_form.html.twig') }}
                    {{ include('usuario/_delete_form.html.twig') }}
                    <a class="btn btn-dark" href="{{ path('home') }}"><img src="{{ asset('data/images/arrow_white.png') }}" class="show-img-index"/></a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

mydreamhouse/templates/usuario/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Usuario index{% endblock %}

{% block body %}
    <h1>Lista de usuarios</h1>

    <table id="tabla-usuarios" class="table">
        <thead id="thead-usuarios" class="thead-dark">
            <tr class="th-usuario">
                <th>Id</th>
                <th>Imagen Usuario</th>
                <th>Email</th>
                <th>Roles</th>
                <th>Contraseña</th>
                <th>Nombre</th>
                <th>Apellidos</th>
                <th>Fecha Nacimiento</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        {% for usuario in usuarios %}
            <tr>
                <td data-title="Id">{{ usuario.id }}</td>
                <td data-title="Foto de perfil"><img src="{{ usuario.imagenUsu ? asset('data/images/usuarios/'~usuario.imagenUsu) : asset('data/images/usuarios/user-image.png') }}" class="user-img-index"/></td>
                <td data-title="Email">{{ usuario.email }}</td>
                <td data-title="Role">{{ usuario.roles ? usuario.roles|json_encode : '' }}</td>
                <td data-title="Contraseña"><span id="passwd">{{ usuario.password }}</span></td>
                <td data-title="Nombre">{{ usuario.nombre }}</td>
                <td data-title="Apellidos">{{ usuario.apellidos }}</td>
                <td data-title="Fecha de nacimiento">{{ usuario.fechaNac ? usuario.fechaNac|date('d-m-Y') : '' }}</td>
                <td data-title="Acciones">
                    <a href="{{ path('usuario_show', {'id': usuario.id}) }}"><img src="{{ asset('data/images/show.png') }}" class="show-img-index"/></a>
                    <a href="{{ path('usuario_edit', {'id': usuario.id}) }}"><img src="{{ asset('data/images/edit.png') }}" class="edit-img-index"/></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">Sin usuarios registrados</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

mydreamhouse/templates/usuario/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nuevo usuario{% endblock %}
{% block stylesheets %}
			<link href="{{ asset('bootstrap/css/bootstrap.css') }}" type="text/css" rel="stylesheet"/>
			<link href="{{ asset('css/main.css') }}" type="text/css" rel="stylesheet"/>
            <link href="{{ asset('css/styles.css') }}" type="text/css" rel="stylesheet"/>
{% endblock %}
{% block body %}
<div class="container pt-1 pb-1"  style="background-image: url('/data/images/fondos/casaFondoOpacity.png');">
    <div id="div-regis">
        <div id="div-img-regis">
            <img id="img-regis" src="/data/images/fondos/casaFondo4recortada.jpg"></img>
        </div>
        <div class="" id="div-form-regis">
            <h3 class="text-center pt-3">Registrar</h3>
            <span id="spanuser">{{ include('usuario/_form.html.twig') }}</span>
        </div>
    </div>
</div>
{% endblock %}

mydreamhouse/templates/usuario/redirect.html.twig
{% extends 'base.html.twig' %}

{% block title %}Usuario creado!!
{% endblock %}

{% block body %}
	<style>
		.example-wrapper {
			margin: 1em auto;
			max-width: 800px;
			width: 95%;
			font: 18px / 1.5 sans-serif;
		}
		.example-wrapper code {
			background: #F5F5F5;
			padding: 2px 6px;
		}
	</style>

	<div class="example-wrapper">
        <p> ✔️ Usuario creado satisfactoriamente</p>
		<button class="btn btn-lg btn-primary">
			<a class="text-light" href="{{ path('index')}}">Regresar al Home.</a>
		</button>
	</div>
{% endblock %}

mydreamhouse/templates/usuario/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tu perfil{% endblock %}
{% block stylesheets %}
	<link href="{{ asset('bootstrap/css/bootstrap.css') }}" type="text/css" rel="stylesheet"/>
	<link href="{{ asset('css/styles.css') }}" type="text/css" rel="stylesheet"/>
	<link href="{{ asset('css/main.css') }}" type="text/css" rel="stylesheet"/>
{% endblock %}

{% block body %}
    <div class="container pt-5 pb-5" style="background-image: url('/data/images/fondos/casaFondoOpacity.png');">
        
        <div class="pt-5 pb-3 bg-light pl-5 pr-5" id="usu-show">
            <h1 class="text-center">{{ usuario.nombre }} {{ usuario.apellidos }}</h1>

            <img src="{{ usuario.imagenUsu ? asset('data/images/usuarios/'~usuario.imagenUsu) : asset('data/images/usuarios/user-image.png') }}" class="user-img"/>
            
            <table class="table">
                <tbody>
                    <tr>
                        <th class="bg-dark text-light">Email</th>
                        <td class="">{{ usuario.email }}</td>
                    </tr>
                    <tr>
                        <th class="bg-dark text-light">Nombre</th>
                        <td class="">{{ usuario.nombre }}</td>
                    </tr>
                    <tr>
                        <th class="bg-dark text-light">Apellidos</th>
                        <td class="">{{ usuario.apellidos }}</td>
                    </tr>
                    <tr>
                        <th class="bg-dark text-light">Fecha Nacimiento:</th>
                        <td class="">{{ usuario.fechaNac ? usuario.fechaNac|date('d-m-Y') : '' }}</td>
                    </tr>
                </tbody>
            </table>
            {% if usuario.email == app.user.email %}
                <a class="btn btn-info ml-2 mr-2 my-2 rounded" href="{{ path('usuario_edit', {'id': usuario.id}) }}">Editar<img class="ml-1" src="{{ asset('data/images/white_edit.png') }}"/></a>
                <a class="btn btn-dark margin my-2 mx-2" href="{{ path('home') }}"><img src="{{ asset('data/images/arrow_white.png') }}" class="show-img-index"/>Regresar al home</a>
            {% else %}
            <form id="form-show-user" method="post" action="{{ path('usuario_delete', {'id': usuario.id}) }}" onsubmit="return confirm('Seguro que quieres borrar a este usuario?');">
                <input type="hidden" name="_method" value="DELETE">
                <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ usuario.id) }}">
                <button class="btn btn-danger profile-button">Eliminar<img class="ml-1" src="{{ asset('data/images/white_trash.png') }}"/></button>
                <a class="btn btn-info ml-2 mr-2 my-2 rounded" href="{{ path('usuario_edit', {'id': usuario.id}) }}">Editar<img class="ml-1" src="{{ asset('data/images/white_edit.png') }}"/></a>
                <a class="btn btn-dark margin my-2 mx-2" href="{{ path('home') }}"><img src="{{ asset('data/images/arrow_white.png') }}" class="show-img-index"/>Regresar al home</a>
            </form>
            {% endif %}
        </div>
    </div>
{% endblock %}