mydreamhouse/src/Entity/Ciudad.php
<?php

namespace App\Entity;

use App\Repository\CiudadRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Mapping\ClassMetadata;

/**
 * @ORM\Entity(repositoryClass=CiudadRepository::class)
 * @UniqueEntity(fields="nombre_ciudad", message="Ya existe esa ciudad!!!")
 */
class Ciudad
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=25, unique=true)
     */
    protected $nombre_ciudad;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombreCiudad(): ?string
    {
        return $this->nombre_ciudad;
    }

    public function setNombreCiudad(string $nombre_ciudad): self
    {
        $this->nombre_ciudad = $nombre_ciudad;

        return $this;
    }

    public function __toString()
    {
        return $this->nombre_ciudad;
    }
}

mydreamhouse/src/Form/CiudadType.php
<?php

namespace App\Form;

use App\Entity\Ciudad;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CiudadType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nombre_ciudad', TextType::class, [
                'label' => 'Ciudad',
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Ciudad::class,
        ]);
    }
}

mydreamhouse/src/Controller/CiudadController.php
<?php

namespace App\Controller;

use App\Entity\Ciudad;
use App\Entity\Casa;
use App\Form\CiudadType;
use App\Repository\CiudadRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/ciudad")
 */
class CiudadController extends AbstractController
{
    /**
     * @Route("/", name="ciudad_index", methods={"GET"})
     */
    public function index(CiudadRepository $ciudadRepository): Response
    {
        return $this->render('ciudad/index.html.twig', [
            'ciudads' => $ciudadRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="ciudad_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $ciudad = new Ciudad();
        $form = $this->createForm(CiudadType::class, $ciudad);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($ciudad);
            $entityManager->flush();

            return $this->redirectToRoute('ciudad_index');
        }

        return $this->render('ciudad/new.html.twig', [
            'ciudad' => $ciudad,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/show/{id}", name="ciudad_show", methods={"GET"})
     */
    public function show(Ciudad $ciudad): Response
    {
        return $this->render('ciudad/show.html.twig', [
            'ciudad' => $ciudad,
        ]);
    }

    /**
     * @Route("/edit/{id}", name="ciudad_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Ciudad $ciudad): Response
    {
        $form = $this->createForm(CiudadType::class, $ciudad);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('ciudad_index');
        }

        return $this->render('ciudad/edit.html.twig', [
            'ciudad' => $ciudad,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/delete/{id}", name="ciudad_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Ciudad $ciudad): Response
    {
        $casa = new Casa;
        $q = true;

        foreach ($casa as $c) {
            if ($c->getIdCiu() == $ciudad->getId()) {
                $q = false;
            }
        }

        if (!$q) {
            if ($this->isCsrfTokenValid('delete' . $ciudad->getId(), $request->request->get('_token')) && $q) {
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->remove($ciudad);
                $entityManager->flush();
            }
        } else echo '<script>alert("No se ha podido eliminar la ciudad\nPuede que haya alguna casa que pertenece a la ciudad escogida");</script>';

        return $this->redirectToRoute('ciudad_index');
    }
}

mydreamhouse/templates/ciudad/_delete_form.html.twig
<form method="post" class="w-100" action="{{ path('ciudad_delete', {'id': ciudad.id}) }}" onsubmit="return confirm('¿Quieres borrar la ciudad?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ciudad.id) }}">
    <button class="btn btn-danger my-2 w-100" id="btn-delete-ciu">Eliminar<img class="ml-1" src="{{ asset('data/images/white_trash.png') }}"/></button>
</form>

mydreamhouse/templates/ciudad/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button id="btn-save-ciu" class="w-100 btn btn-info my-2">{{ button_label|default('Guardar') }}<img class="ml-1" src="{{ asset('data/images/save.png') }}"/></button>
{{ form_end(form) }}

mydreamhouse/templates/ciudad/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Ciudad{% endblock %}

{% block body %}
    <div class="container pt-2 pb-2 pl-3" style="background-image: url('/data/images/fondos/casaFondoOpacity.png');">
        <div id="div-ciudad-regis">
            <div id="div-imgciudad-regis">
                <img id="img-ciudad-regis" src="/data/images/fondos/casaFondo4.jpg"></img>
            </div>
            <div class="" id="div-formciu-regis">
              <h2 class="text-center">Editar Ciudad</h2>
              <div class="my-2 btn-group-vertical btn-group-justified" id="edit-form">
                  {{ include('ciudad/_form.html.twig') }}
                  {{ include('ciudad/_delete_form.html.twig') }}
                  <a class="btn btn-dark my-2 w-100" id="volver-editciu" href="{{ path('ciudad_index') }}"><img src="{{ asset('data/images/arrow_white.png') }}"/>Volver a la lista</a>
              </div>
            </div>
        </div>
    </div>
{% endblock %}

mydreamhouse/templates/ciudad/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ciudad index{% endblock %}

{% block body %}
    <h1>Lista de ciudades</h1>

    <table class="table" id="tabla-ciudades">
        <thead class="thead-dark">
            <tr>
                <th>Id</th>
                <th>Ciudad</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        {% for ciudad in ciudads %}
            <tr>
                <td>{{ ciudad.id }}</td>
                <td>{{ ciudad.nombreCiudad }}</td>
                <td>
                    <a class="btn btn-info ml-1 mt-1" href="{{ path('ciudad_show', {'id': ciudad.id}) }}">ver<img class="ml-1" src="{{ asset('data/images/white-show.png') }}"/></a>
                    <a class="btn btn-info ml-1 mt-1" href="{{ path('ciudad_edit', {'id': ciudad.id}) }}">editar<img class="ml-1" src="{{ asset('data/images/white_edit.png') }}"/></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
            <tr>
                <td></td>
                <td></td>
                <td><a class="btn btn-dark my-2 ml-1" href="{{ path('ciudad_new') }}">Crear nueva ciudad</a></td>
            </tr>
        </tbody>
    </table>

    
{% endblock %}

mydreamhouse/templates/ciudad/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nueva Ciudad{% endblock %}

{% block body %}
    <div class="container pt-2 pb-2 pl-3" style="background-image: url('/data/images/fondos/casaFondoOpacity.png');">
        <div id="div-ciudad-regis">
            <div id="div-imgciudad-regis">
                <img id="img-ciudad-regis" src="/data/images/fondos/casaFondo4.jpg"></img>
            </div>
            <div class="" id="div-formciu-regis">
                <h2 class="text-center pb-4">Registrar ciudad</h2>
                {{ include('ciudad/_form.html.twig') }}
                <a class="btn btn-dark my-2 w-100" id="volver-editciu" href="{{ path('ciudad_index') }}"><img src="{{ asset('data/images/arrow_white.png') }}"/>Volver a la lista</a>
            </div>
        </div>
    </div>
{% endblock %}

mydreamhouse/templates/ciudad/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ciudad{% endblock %}

{% block body %}
  <div class="container pt-1 pb-1 pl-3" style="background-image: url('/data/images/fondos/casaFondoOpacity.png');">
        <div id="div-ciudad-regis">
            <div id="div-imgciudad-regis">
                <img id="img-ciudad-regis" src="/data/images/fondos/casaFondo4.jpg"></img>
            </div>
            <div class="" id="div-ciu-show">
                <h2 class="text-center">Ciudad</h2>

                <table class="table">
                    <tbody>
                        <tr>
                            <th class="bg-dark text-light">Ciudad</th>
                            <td>{{ ciudad.nombreCiudad }}</td>
                        </tr>
                    </tbody>
                </table>
                <div class="btn-group w-100 pr-2">
                  <a class="btn btn-dark my-2 ml-2 w-100" href="{{ path('ciudad_index') }}"><img src="{{ asset('data/images/arrow_white.png') }}"/>Volver a la lista</a>
                  <a class="btn btn-info ml-2 mr-2 my-2 rounded w-100" href="{{ path('ciudad_edit', {'id': ciudad.id}) }}">Editar<img class="ml-1" src="{{ asset('data/images/white_edit.png') }}"/></a>
                  {{ include('ciudad/_delete_form.html.twig') }}
                </div>
            </div>
          </div>
  </div>
{% endblock %}