mydreamhouse/src/Entity/Propietario.php
<?php

namespace App\Entity;

use App\Repository\PropietarioRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PropietarioRepository::class)
 */
class Propietario
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $nombre;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $email_prop;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $telefono;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $tipo_propietario;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(?string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getEmailProp(): ?string
    {
        return $this->email_prop;
    }

    public function setEmailProp(?string $email_prop): self
    {
        $this->email_prop = $email_prop;

        return $this;
    }

    public function getTelefono(): ?int
    {
        return $this->telefono;
    }

    public function setTelefono(?int $telefono): self
    {
        $this->telefono = $telefono;

        return $this;
    }

    public function getTipoPropietario(): ?string
    {
        return $this->tipo_propietario;
    }

    public function setTipoPropietario(?string $tipo_propietario): self
    {
        $this->tipo_propietario = $tipo_propietario;

        return $this;
    }

    public function __toString()
    {
        return $this->nombre;
    }
}

mydreamhouse/src/Form/PropietarioType.php
<?php

namespace App\Form;

use App\Entity\Propietario;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropietarioType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nombre')
            ->add('email_prop')
            ->add('telefono')
            ->add('tipo_propietario')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Propietario::class,
        ]);
    }
}

mydreamhouse/src/Controller/PropietarioController.php
<?php

namespace App\Controller;

use App\Entity\Propietario;
use App\Form\PropietarioType;
use App\Repository\PropietarioRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/propietario")
 */
class PropietarioController extends AbstractController
{
    /**
     * @Route("/", name="propietario_index", methods={"GET"})
     */
    public function index(PropietarioRepository $propietarioRepository): Response
    {
        return $this->render('propietario/index.html.twig', [
            'propietarios' => $propietarioRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="propietario_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $propietario = new Propietario();
        $form = $this->createForm(PropietarioType::class, $propietario);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($propietario);
            $entityManager->flush();

            return $this->redirectToRoute('propietario_index');
        }

        return $this->render('propietario/new.html.twig', [
            'propietario' => $propietario,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/show/{id}", name="propietario_show", methods={"GET"})
     */
    public function show(Propietario $propietario): Response
    {
        return $this->render('propietario/show.html.twig', [
            'propietario' => $propietario,
        ]);
    }

    /**
     * @Route("/edit/{id}", name="propietario_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Propietario $propietario): Response
    {
        $form = $this->createForm(PropietarioType::class, $propietario);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('propietario_index');
        }

        return $this->render('propietario/edit.html.twig', [
            'propietario' => $propietario,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/delete/{id}", name="propietario_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Propietario $propietario): Response
    {
        if ($this->isCsrfTokenValid('delete'.$propietario->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($propietario);
            $entityManager->flush();
        }

        return $this->redirectToRoute('propietario_index');
    }
}

mydreamhouse/templates/propietario/_delete_form.html.twig
<form method="post" action="{{ path('propietario_delete', {'id': propietario.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ propietario.id) }}">
    <button class="btn">Delete</button>
</form>

mydreamhouse/templates/propietario/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

mydreamhouse/templates/propietario/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Propietario{% endblock %}

{% block body %}
    <h1>Edit Propietario</h1>

    {{ include('propietario/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('propietario_index') }}">back to list</a>

    {{ include('propietario/_delete_form.html.twig') }}
{% endblock %}

mydreamhouse/templates/propietario/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Propietario index{% endblock %}

{% block body %}
    <h1>Propietario index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Email_prop</th>
                <th>Telefono</th>
                <th>Tipo_propietario</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for propietario in propietarios %}
            <tr>
                <td>{{ propietario.id }}</td>
                <td>{{ propietario.nombre }}</td>
                <td>{{ propietario.emailProp }}</td>
                <td>{{ propietario.telefono }}</td>
                <td>{{ propietario.tipoPropietario }}</td>
                <td>
                    <a href="{{ path('propietario_show', {'id': propietario.id}) }}">show</a>
                    <a href="{{ path('propietario_edit', {'id': propietario.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('propietario_new') }}">Create new</a>
{% endblock %}

mydreamhouse/templates/propietario/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Propietario{% endblock %}

{% block body %}
    <h1>Create new Propietario</h1>

    {{ include('propietario/_form.html.twig') }}

    <a href="{{ path('propietario_index') }}">back to list</a>
{% endblock %}

mydreamhouse/templates/propietario/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Propietario{% endblock %}

{% block body %}
    <h1>Propietario</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ propietario.id }}</td>
            </tr>
            <tr>
                <th>Nombre</th>
                <td>{{ propietario.nombre }}</td>
            </tr>
            <tr>
                <th>Email_prop</th>
                <td>{{ propietario.emailProp }}</td>
            </tr>
            <tr>
                <th>Telefono</th>
                <td>{{ propietario.telefono }}</td>
            </tr>
            <tr>
                <th>Tipo_propietario</th>
                <td>{{ propietario.tipoPropietario }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('propietario_index') }}">back to list</a>

    <a href="{{ path('propietario_edit', {'id': propietario.id}) }}">edit</a>

    {{ include('propietario/_delete_form.html.twig') }}
{% endblock %}