mydreamhouse/src/Entity/Casa.php
<?php

namespace App\Entity;

use App\Repository\CasaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CasaRepository::class)
 */
class Casa
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $direccion;

    /**
     * @ORM\Column(type="string", length=5, nullable=true)
     */
    private $cp;

    /**
     * @ORM\Column(type="string", length=8, nullable=true)
     */
    private $tipo_venta;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $m2;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $precio;

    /**
     * @ORM\Column(type="string", length=25, nullable=true)
     */
    private $tipo_casa;

    /**
     * @ORM\ManyToOne(targetEntity=Ciudad::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_ciu;

    /**
     * @ORM\ManyToOne(targetEntity=Usuario::class)
     */
    private $id_usu;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $titulo;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $descripcion;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $habitaciones;

    /**
     * @ORM\OneToMany(targetEntity=Fotos::class, mappedBy="id_casa", orphanRemoval=true)
     */
    private $fotos;

    /**
     * @ORM\ManyToOne(targetEntity=Propietario::class)
     * @ORM\JoinColumn(nullable=true)
     */
    private $id_prop;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $banos;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $coordenadas;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $especificaciones;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $prioridad;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $extra1;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $extra2;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $activo;

    public function __construct()
    {
        $this->fotos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDireccion(): ?string
    {
        return $this->direccion;
    }

    public function setDireccion(string $direccion): self
    {
        $this->direccion = $direccion;

        return $this;
    }

    public function getCp(): ?string
    {
        return $this->cp;
    }

    public function setCp(?string $cp): self
    {
        $this->cp = $cp;

        return $this;
    }

    public function getTipoVenta(): ?string
    {
        return $this->tipo_venta;
    }

    public function setTipoVenta(?string $tipo_venta): self
    {
        $this->tipo_venta = $tipo_venta;

        return $this;
    }

    public function getM2(): ?int
    {
        return $this->m2;
    }

    public function setM2(?int $m2): self
    {
        $this->m2 = $m2;

        return $this;
    }

    public function getPrecio(): ?int
    {
        return $this->precio;
    }

    public function setPrecio(?int $precio): self
    {
        $this->precio = $precio;

        return $this;
    }

    public function getTipoCasa(): ?string
    {
        return $this->tipo_casa;
    }

    public function setTipoCasa(?string $tipo_casa): self
    {
        $this->tipo_casa = $tipo_casa;

        return $this;
    }

    public function getIdCiu(): ?Ciudad
    {
        return $this->id_ciu;
    }

    public function setIdCiu(?Ciudad $id_ciu): self
    {
        $this->id_ciu = $id_ciu;

        return $this;
    }

    public function getIdUsu(): ?Usuario
    {
        return $this->id_usu;
    }

    public function setIdUsu(?Usuario $id_usu): self
    {
        $this->id_usu = $id_usu;

        return $this;
    }

    public function getTitulo(): ?string
    {
        return $this->titulo;
    }

    public function setTitulo(?string $titulo): self
    {
        $this->titulo = $titulo;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->descripcion;
    }

    public function setDescripcion(?string $descripcion): self
    {
        $this->descripcion = $descripcion;

        return $this;
    }

    public function getHabitaciones(): ?int
    {
        return $this->habitaciones;
    }

    public function setHabitaciones(?int $habitaciones): self
    {
        $this->habitaciones = $habitaciones;

        return $this;
    }

    /**
     * @return Collection|Fotos[]
     */
    public function getFotos(): Collection
    {
        return $this->fotos;
    }

    public function addFoto(Fotos $foto): self
    {
        if (!$this->fotos->contains($foto)) {
            $this->fotos[] = $foto;
            $foto->setIdCasa($this);
        }

        return $this;
    }

    public function removeFoto(Fotos $foto): self
    {
        if ($this->fotos->contains($foto)) {
            $this->fotos->removeElement($foto);
            // set the owning side to null (unless already changed)
            if ($foto->getIdCasa() === $this) {
                $foto->setIdCasa(null);
            }
        }

        return $this;
    }

    public function getIdProp(): ?Propietario
    {
        return $this->id_prop;
    }

    public function setIdProp(?Propietario $id_prop): self
    {
        $this->id_prop = $id_prop;

        return $this;
    }

    public function getBanos(): ?int
    {
        return $this->banos;
    }

    public function setBanos(?int $banos): self
    {
        $this->banos = $banos;

        return $this;
    }

    public function getCoordenadas(): ?string
    {
        return $this->coordenadas;
    }

    public function setCoordenadas(?string $coordenadas): self
    {
        $this->coordenadas = $coordenadas;

        return $this;
    }

    public function getEspecificaciones(): ?string
    {
        return $this->especificaciones;
    }

    public function setEspecificaciones(?string $especificaciones): self
    {
        $this->especificaciones = $especificaciones;

        return $this;
    }

    public function getPrioridad(): ?int
    {
        return $this->prioridad;
    }

    public function setPrioridad(?int $prioridad): self
    {
        $this->prioridad = $prioridad;

        return $this;
    }

    public function getExtra1(): ?string
    {
        return $this->extra1;
    }

    public function setExtra1(?string $extra1): self
    {
        $this->extra1 = $extra1;

        return $this;
    }

    public function getExtra2(): ?string
    {
        return $this->extra2;
    }

    public function setExtra2(?string $extra2): self
    {
        $this->extra2 = $extra2;

        return $this;
    }

    public function getActivo(): ?bool
    {
        return $this->activo;
    }

    public function setActivo(?bool $activo): self
    {
        $this->activo = $activo;

        return $this;
    }

    public function __toString()
    {
        return $this->titulo;
    }
}

mydreamhouse/src/Controller/CasaController.php
<?php

namespace App\Controller;

use App\Entity\Casa;
use App\Entity\Fotos;
use App\Form\CasaType;
use App\Repository\CasaRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Finder\SplFileInfo;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;

//use function App\acceso;

/**
 * @Route("/casa")
 */
class CasaController extends AbstractController
{
    /**
     * @Route("/{page}", name="casa_index", methods={"GET","POST"}, requirements={"page"="\d+"})
     */
    public function index(CasaRepository $casaRepository, Request $request, $page = 1): Response
    {
        $usu = $this->getUser();
        $limit = 10;

        $tipo_venta = '';
        $tipo_casa = '';
        $id_ciu = '';
        $m2min = '';
        $m2max = '';
        $preciomin = '';
        $preciomax = '';
        $h = [];
        $b = [];

        if ($request->getMethod() == "POST") {

            $h = $request->request->get('h');
            $b = $request->request->get('b');

            $tipo_venta = ($request->request->get('casa')['tipo_venta']) ? $request->request->get('casa')['tipo_venta'] : '';
            $tipo_casa = ($request->request->get('casa')['tipo_casa']) ? $request->request->get('casa')['tipo_casa'] : '';
            $id_ciu = ($request->request->get('casa')['id_ciu']) ? $request->request->get('casa')['id_ciu'] : '';

            $m2min = ($request->request->get('m2min')) ? $request->request->get('m2min') : '';
            $m2max = ($request->request->get('m2max')) ? $request->request->get('m2max') : '';
            $preciomin = ($request->request->get('preciomin')) ? $request->request->get('preciomin') : '';
            $preciomax = ($request->request->get('preciomax')) ? $request->request->get('preciomax') : '';

            if ($request->request->get('h') != null) {
                $h = $request->request->get('h');
                for ($i = 0; $i < 5; $i++) if (!array_key_exists($i, $h)) $h[$i] = '';
            }
            if ($request->request->get('b') != null) {
                $b = $request->request->get('b');
                for ($i = 0; $i < 5; $i++) if (!array_key_exists($i, $b)) $b[$i] = '';
            }


            $casas = $casaRepository->getCasasFiltrado($page, $limit, $request->request);
        } else $casas = $casaRepository->getAllCasas($page, $limit);

        $casasPaginadas = $casas['paginator'];
        $casasCompleto =  $casas['query'];
        $maxPages = ceil($casas['paginator']->count() / $limit);

        $casa = new Casa();
        $form = $this->createForm(CasaType::class, $casa);
        $form->handleRequest($request);

        if ($usu == null) {

            return $this->render('casa/user/indexuser.html.twig', [
                'casas' => $casasPaginadas,
                'maxPages' => $maxPages,
                'thisPage' => $page,
                'all_items' => $casasCompleto,
                'form' => $form->createView(),
                'request' => $request,
                'method' => $request->getMethod(),
                'tipo_venta' => $tipo_venta,
                'tipo_casa' => $tipo_casa,
                'id_ciu' => $id_ciu,
                'm2min' => $m2min,
                'm2max' => $m2max,
                'preciomin' => $preciomin,
                'preciomax' => $preciomax,
                'h' => $h,
                'b' => $b,
            ]);
        } else {

            if ($casaRepository->acceso($usu->getRoles()) == 'admin') {

                return $this->render('casa/index.html.twig', [
                    'casas' => $casasPaginadas,
                    'maxPages' => $maxPages,
                    'thisPage' => $page,
                    'all_items' => $casasCompleto,
                    'form' => $form->createView(),
                    'request' => $request,
                    'method' => $request->getMethod(),
                    'tipo_venta' => $tipo_venta,
                    'tipo_casa' => $tipo_casa,
                    'id_ciu' => $id_ciu,
                    'm2min' => $m2min,
                    'm2max' => $m2max,
                    'preciomin' => $preciomin,
                    'preciomax' => $preciomax,
                    'h' => $h,
                    'b' => $b,
                ]);
            } else {

                return $this->render('casa/user/indexuser.html.twig', [
                    'casas' => $casasPaginadas,
                    'maxPages' => $maxPages,
                    'thisPage' => $page,
                    'all_items' => $casasCompleto,
                    'form' => $form->createView(),
                    'request' => $request,
                    'method' => $request->getMethod(),
                    'tipo_venta' => $tipo_venta,
                    'tipo_casa' => $tipo_casa,
                    'id_ciu' => $id_ciu,
                    'm2min' => $m2min,
                    'm2max' => $m2max,
                    'preciomin' => $preciomin,
                    'preciomax' => $preciomax,
                    'h' => $h,
                    'b' => $b,
                ]);
            }
        }
    }

    /**
     * @Route("/new", name="casa_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $q = true;

        $casa = new Casa();
        $form = $this->createForm(CasaType::class, $casa);
        $form->handleRequest($request);

        $entityManager = $this->getDoctrine()->getManager();

        if ($form->isSubmitted() && $form->isValid()) {

            /** @var UploadedFile $brochureFile */
            $brochureFile = $form->get('fotos')->getData();

            $i = 0;
            foreach ($brochureFile as $file) {
                $ext = $file->guessExtension();
                if ($ext != 'jpg' && $ext != 'png' && $ext != 'jpeg' && $ext != 'gif') {
                    $q = false;
                    return $this->render('casa/new.html.twig', [
                        'casa' => $casa,
                        'form' => $form->createView(),
                        'q' => $q
                    ]);
                }

                // this condition is needed because the 'brochure' field is not required
                // so the PDF file must be processed only when a file is uploaded
                if ($file && $q) {

                    $foto[$i] = new Fotos;
                    $originalFilename = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
                    // this is needed to safely include the file name as part of the URL
                    $safeFilename = transliterator_transliterate('Any-Latin; Latin-ASCII; [^A-Za-z0-9_] remove; Lower()', $originalFilename);
                    $newFilename = $safeFilename . '_' . uniqid() . '.' . $file->guessExtension();

                    /* $ext = $file->guessExtension();
                    if ($ext != 'jpg' && $ext != 'png' && $ext != 'jpeg' && $ext != 'gif') throw new FileException("Formato inválido"); */

                    // Move the file to the directory where brochures are stored
                    try {
                        $file->move(
                            $this->getParameter('img_casa'),
                            $newFilename
                        );

                        $foto[$i]->setRuta($newFilename);
                        $foto[$i]->setPrincipal($i == 0 ? 1 : 0);
                        $casa->addFoto($foto[$i]);
                        $entityManager->persist($foto[$i]);
                    } catch (FileException $e) {
                        // ... handle exception if something happens during file upload
                    }

                    // actualiza la propiedad 'brochureFilename' para guardar el nombre archivo
                    $i++;
                }
            }

            $entityManager->persist($casa);
            $entityManager->flush();

            return $this->redirectToRoute('casa_index');
        }

        return $this->render('casa/new.html.twig', [
            'casa' => $casa,
            'form' => $form->createView(),
            'q' => $q
        ]);
    }

    /**
     * @Route("/show/{id}", name="casa_show", methods={"GET"})
     */
    public function show(Casa $casa, CasaRepository $casaRepository): Response
    {
        $usu = $this->getUser();

        if ($usu == null) {

            return $this->render('casa/user/showuser.html.twig', [
                'casa' => $casa,
            ]);
        } else {

            if ($casaRepository->acceso($usu->getRoles()) == 'admin') {

                return $this->render('casa/show.html.twig', [
                    'casa' => $casa,
                ]);
            } else {

                return $this->render('casa/user/showuser.html.twig', [
                    'casa' => $casa,
                ]);
            }
        }
    }

    /**
     * @Route("/edit/{id}", name="casa_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Casa $casa): Response
    {
        $q = true;
        
        $form = $this->createForm(CasaType::class, $casa);
        $form->handleRequest($request);

        $entityManager = $this->getDoctrine()->getManager();

        if ($form->isSubmitted() && $form->isValid()) {

            /** @var UploadedFile $brochureFile */
            $brochureFile = $form->get('fotos')->getData();

            $i = 0;
            foreach ($brochureFile as $file) {
                $ext = $file->guessExtension();
                if ($ext != 'jpg' && $ext != 'png' && $ext != 'jpeg' && $ext != 'gif') {
                    $q = false;
                    return $this->render('casa/new.html.twig', [
                        'casa' => $casa,
                        'form' => $form->createView(),

mydreamhouse/templates/casa/_delete_form.html.twig
<form method="post" action="{{ path('casa_delete', {'id': casa.id}) }}" onsubmit="return confirm('¿Está seguro de borrar el anuncio?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ casa.id) }}">
    <button class="btn btn-danger ml-2 my-2 pb-2 py-2">Eliminar<img src="{{ asset('data/images/white_trash.png') }}"/></button>
</form>

mydreamhouse/templates/casa/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-info ml-2 my-2">{{ button_label|default('Guardar') }}<img src="{{ asset('data/images/save.png') }}"/></button>
    <a class="btn btn-dark my-2 ml-2" href="{{ path('casa_index') }}"><img src="{{ asset('data/images/arrow_white.png') }}"/>Volver a la lista</a>
{{ form_end(form) }}

mydreamhouse/templates/casa/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editar Casa{% endblock %}

{% block body %}
<div class="container pt-1 pb-1"  style="background-image: url('/data/images/fondos/casaFondoOpacity.png');">
    <div id="div-casas-regis">
        <div id="div-imgcasas-regis">
            <img id="img-casas-regis" src="/data/images/fondos/casaFondo4recortada.jpg"></img>
        </div>
        <div class="pl-3 pr-3" id="div-formcasas-regis">
        <h2 class="text-center pt-3 pb-3">Editar Casa</h2>

        <div class="w-100">
            {{ include('casa/_form.html.twig') }}
            {{ include('casa/_delete_form.html.twig') }}
        </div>
    </div>
</div>
{% endblock %}

mydreamhouse/templates/casa/hidden.html.twig
<input type="hidden" name="casa[tipo_venta]" value="{{ tipo_venta }}">
<input type="hidden" name="casa[tipo_casa]" value="{{ tipo_casa }}">
<input type="hidden" name="casa[id_ciu]" value="{{ id_ciu }}">

<input type="hidden" name="m2min" value="{{ m2min }}">
<input type="hidden" name="m2max" value="{{ m2max }}">

<input type="hidden" name="preciomin" value="{{ preciomin }}">
<input type="hidden" name="preciomax" value="{{ preciomax }}">

{% if h != null %}
	<input type="hidden" name="h[1]" value="{{ h[1] }}">
	<input type="hidden" name="h[2]" value="{{ h[2] }}">
	<input type="hidden" name="h[3]" value="{{ h[3] }}">
	<input type="hidden" name="h[4]" value="{{ h[4] }}">
{% endif %}

{% if b != null %}
	<input type="hidden" name="b[1]" value="{{ b[1] }}">
	<input type="hidden" name="b[2]" value="{{ b[2] }}">
	<input type="hidden" name="b[3]" value="{{ b[3] }}">
	<input type="hidden" name="b[4]" value="{{ b[4] }}">
{% endif %}

mydreamhouse/templates/casa/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Casa index
{% endblock %}

{% block body %}

	<br>
	<nav class="nav justify-content-center">
		{{ include('casa/paginacion.html.twig')}}
	</nav>

	<br>

	<div class="">
		<div class="">

			{{ include('casa/filtros.html.twig') }}

		</div>
		<div class="col-9">
			{% for casa in casas %}
				{% if casa.getIdUsu == null %}

					<div class="ctn-house">
						<div class="ctn-image-house">
							{% set counter = ( counter | default(0) ) + 1 %}
							<div id="slider{{ counter }}" class="carousel slide" data-interval="false">

								<div class="carousel-inner">
									{% for foto in casa.fotos %}
										{% if foto.principal == 1 %}
											<div class="carousel-item active">
												<img class="d-block w-100 img-fluid" src="{{ foto.ruta|slice(0,8) == 'https://' ? foto.ruta : asset('data/images/casas/'~ foto.ruta) }}" alt="Imagen principal">
											</div>
										{% else %}
											<div class="carousel-item">
												<img class="d-block w-100 img-fluid" src="{{ foto.ruta|slice(0,8) == 'https://' ? foto.ruta : asset('data/images/casas/'~ foto.ruta) }}" alt="Imagen secundaria">
											</div>
										{% endif %}
									{% else %}
										<p>No se ha encontrado ninguna foto</p>
									{% endfor %}
								</div>

								<a class="carousel-control-prev" href="#slider{{ counter }}" role="button" data-slide="prev">
									<span class="carousel-control-prev-icon" aria-hidden="true"></span>
									<span class="sr-only">Previous</span>
								</a>
								<a class="carousel-control-next" href="#slider{{ counter }}" role="button" data-slide="next">
									<span class="carousel-control-next-icon" aria-hidden="true"></span>
									<span class="sr-only">Next</span>
								</a>
							</div>
						</div>

						<div class="info-description">

							<h3>
								<span>
									<a href="{{ path('casa_show', {'id': casa.id}) }}" class="a-title">{{ casa.titulo }}</a>
								</span>
							</h3>
							<div class="price">
								<span>{{ casa.precio }}€{{ casa.tipoVenta == 'alquiler' ? '/mes' : '' }}</span>
							</div>
							<br>
							<span>{{ casa.direccion }},
								{{ casa.cp }},
								{{ casa.getIdCiu }}</span><br>

							<div class="info-features">
								<div>
									<span>{{ casa.m2 }}
										m² &nbsp;</span>
									<span class="">{{ casa.tipoCasa }}&nbsp;</span>
									<span>{{ casa.habitaciones }}
										habs. &nbsp;</span>
									<span>{{ casa.banos }}
										baños &nbsp;</span>

								</div>
							</div>
							<span>{{ casa.extra1 }}
								&nbsp;</span>
						</div>
						<span>
							<a href="{{ path('casa_show', {'id': casa.id}) }}"><img src="{{ asset('data/images/show.png') }}" class="show-img-index"/></a>
							<a href="{{ path('casa_edit', {'id': casa.id}) }}"><img src="{{ asset('data/images/edit.png') }}" class="show-img-index"/></a>
						</span>
					</div>
				{% endif %}
			{% else %}
				<div class="container" style="margin-left: 25%; margin-bottom: 2%;">
					<h3 class="text-center">No se encontraron casas, introduzca otros datos de búsqueda, por favor.</h3>
				</div>
			{% endfor %}
		</div>
	</div>
	<nav class="nav justify-content-center">
		{{ include('casa/paginacion.html.twig')}}
	</nav>
{% endblock %}

mydreamhouse/templates/casa/mapa.html.twig
	<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
	<script type="text/javascript">

		var coord = "{{ casa.coordenadas }}".split(',');

        var myCenter = new google.maps.LatLng(coord[0], coord[1]);

        var marker = new google.maps.Marker({position: myCenter});

        window.onload = function () {
            var mapOptions = {
                center: myCenter,
                zoom: 16,
                mapTypeId: google.maps.MapTypeId.ROADMAP,
                panControl: false,
                zoomControl: false,
                scaleControl: false
            };
            var map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);
            marker.setMap(map);
        };
	</script>

mydreamhouse/templates/casa/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ casa.titulo }}
{% endblock %}

{% block body %}

	<a class="btn btn-dark my-2 ml-2" href="{{ path('casa_index') }}"><img src="{{ asset('data/images/arrow_white.png') }}"/>Volver a la lista</a>
	<div class="ctn-image-house-show2">
		{% set counter = ( counter | default(0) ) + 1 %}
		<div id="slider{{ counter }}" class="carousel slide" data-interval="false">

			<div class="carousel-inner">
				{% for foto in casa.fotos %}
					{% if foto.principal == 1 %}
						<div class="carousel-item active">
							<img class="d-block w-100 img-fluid" src="{{ foto.ruta|slice(0,8) == 'https://' ? foto.ruta : asset('data/images/casas/'~ foto.ruta) }}" alt="Imagen principal">
						</div>
					{% else %}
						<div class="carousel-item">
							<img class="d-block w-100 img-fluid" src="{{ foto.ruta|slice(0,8) == 'https://' ? foto.ruta : asset('data/images/casas/'~ foto.ruta) }}" alt="Imagen secundaria">
						</div>
					{% endif %}
				{% else %}
					<p>No se ha encontrado ninguna foto</p>
				{% endfor %}
			</div>

			<a class="carousel-control-prev" href="#slider{{ counter }}" role="button" data-slide="prev">
				<span class="carousel-control-prev-icon" aria-hidden="true"></span>
				<span class="sr-only">Previous</span>
			</a>
			<a class="carousel-control-next" href="#slider{{ counter }}" role="button" data-slide="next">
				<span class="carousel-control-next-icon" aria-hidden="true"></span>
				<span class="sr-only">Next</span>
			</a>
			<div class="cabecera-casa">
				<div class="tipo-casa-div">{{ casa.direccion }},
					{{ casa.cp }},
					{{ casa.getIdCiu }}</div>
				<div class="info-derecha">{{ casa.precio }}€{{ casa.tipoVenta == 'alquiler' ? '/mes' : '' }}</div>
			</div>
		</div>
	</div>

	<div class="titulo-casa">
		<h3>{{ casa.titulo }}</h3>
	</div>
	<br>
	<div
		class="desc-casa">

		{# <div class="col-3"></div> #}

		<table class="info-adicional">
			<tr>
				<td>Tipo de casa</td>
				<td>{{ casa.tipoCasa }}</td>
			</tr>
			<tr>
				<td>Metros</td>
				<td>{{ casa.m2 }}
					m²</td>
			</tr>
			<tr>
				<td>Nº Habitaciones</td>
				<td>{{ casa.habitaciones }}</td>
			</tr>
			<tr>
				<td>Nº Baños</td>
				<td>{{ casa.banos }}</td>
			</tr>
			<tr>
				<td>Ciudad</td>
				<td>{{ casa.getIdCiu }}</td>
			</tr>
			<tr>
				<td>Codigo Postal</td>
				<td>{{ casa.cp }}</td>
			</tr>
			<tr>
				<td>Extras</td>
				<td>{{ casa.extra1 }},
					{{ casa.extra2 }}</td>
			</tr>
		</table>
		{# <div class="col-3"></div> #}

		{{ casa.descripcion }}

	</div>

	<br>
	<div class="row">
		<div class="col-2 col-lg-2 col-xl-3"></div>
		<div class="col-8 col-lg-8 col-xl-6 img_fluid" id="map_canvas"></div>
		<div class="col-2 col-lg-2 col-xl-3"></div>
	</div>

	<div class="btn-group">
		<a class="btn btn-info ml-2 mr-2 my-2 rounded" href="{{ path('casa_edit', {'id': casa.id}) }}">Editar<img class="ml-1" src="{{ asset('data/images/white_edit.png') }}"/></a>
		{{ include('casa/_delete_form.html.twig') }}
		<a class="btn btn-dark my-2 ml-2" href="{{ path('casa_index') }}"><img src="{{ asset('data/images/arrow_white.png') }}"/>Volver a la lista</a>
	</div>
	{{ include('casa/mapa.html.twig') }}
{% endblock %}